/*
 * ISD (International Subscriber Dialling) codes.
 * Sourced from the reference list provided by product. India is intentionally
 * kept at the top of the array — the dropdown consumes this order verbatim
 * so the most common code is always the first item without needing to sort.
 *
 * Search on the dropdown matches BOTH the country name and the dial code, so
 * "india" and "+91" (or just "91") both surface the India row.
 */

/** @typedef {{ name: string, dial: string, iso: string }} IsdCode */

/** @type {IsdCode[]} */
export const ISD_CODES = [
  { name: "India", dial: "+91", iso: "IN" },
  { name: "Afghanistan", dial: "+93", iso: "AF" },
  { name: "Aland Islands", dial: "+358", iso: "AX" },
  { name: "Albania", dial: "+355", iso: "AL" },
  { name: "Algeria", dial: "+213", iso: "DZ" },
  { name: "American Samoa", dial: "+1684", iso: "AS" },
  { name: "Andorra", dial: "+376", iso: "AD" },
  { name: "Angola", dial: "+244", iso: "AO" },
  { name: "Anguilla", dial: "+1264", iso: "AI" },
  { name: "Antarctica", dial: "+672", iso: "AQ" },
  { name: "Antigua and Barbuda", dial: "+1268", iso: "AG" },
  { name: "Argentina", dial: "+54", iso: "AR" },
  { name: "Armenia", dial: "+374", iso: "AM" },
  { name: "Aruba", dial: "+297", iso: "AW" },
  { name: "Australia", dial: "+61", iso: "AU" },
  { name: "Austria", dial: "+43", iso: "AT" },
  { name: "Azerbaijan", dial: "+994", iso: "AZ" },
  { name: "Bahamas", dial: "+1242", iso: "BS" },
  { name: "Bahrain", dial: "+973", iso: "BH" },
  { name: "Bangladesh", dial: "+880", iso: "BD" },
  { name: "Barbados", dial: "+1246", iso: "BB" },
  { name: "Belarus", dial: "+375", iso: "BY" },
  { name: "Belgium", dial: "+32", iso: "BE" },
  { name: "Belize", dial: "+501", iso: "BZ" },
  { name: "Benin", dial: "+229", iso: "BJ" },
  { name: "Bermuda", dial: "+1441", iso: "BM" },
  { name: "Bhutan", dial: "+975", iso: "BT" },
  { name: "Bolivia, Plurinational State of", dial: "+591", iso: "BO" },
  { name: "Bosnia and Herzegovina", dial: "+387", iso: "BA" },
  { name: "Botswana", dial: "+267", iso: "BW" },
  { name: "Brazil", dial: "+55", iso: "BR" },
  { name: "British Indian Ocean Territory", dial: "+246", iso: "IO" },
  { name: "Brunei Darussalam", dial: "+673", iso: "BN" },
  { name: "Bulgaria", dial: "+359", iso: "BG" },
  { name: "Burkina Faso", dial: "+226", iso: "BF" },
  { name: "Burundi", dial: "+257", iso: "BI" },
  { name: "Cambodia", dial: "+855", iso: "KH" },
  { name: "Cameroon", dial: "+237", iso: "CM" },
  { name: "Canada", dial: "+1", iso: "CA" },
  { name: "Cape Verde", dial: "+238", iso: "CV" },
  { name: "Cayman Islands", dial: "+345", iso: "KY" },
  { name: "Central African Republic", dial: "+236", iso: "CF" },
  { name: "Chad", dial: "+235", iso: "TD" },
  { name: "Chile", dial: "+56", iso: "CL" },
  { name: "China", dial: "+86", iso: "CN" },
  { name: "Christmas Island", dial: "+61", iso: "CX" },
  { name: "Cocos (Keeling) Islands", dial: "+61", iso: "CC" },
  { name: "Colombia", dial: "+57", iso: "CO" },
  { name: "Comoros", dial: "+269", iso: "KM" },
  { name: "Congo", dial: "+242", iso: "CG" },
  { name: "Congo, The Democratic Republic of the Congo", dial: "+243", iso: "CD" },
  { name: "Cook Islands", dial: "+682", iso: "CK" },
  { name: "Costa Rica", dial: "+506", iso: "CR" },
  { name: "Cote d'Ivoire", dial: "+225", iso: "CI" },
  { name: "Croatia", dial: "+385", iso: "HR" },
  { name: "Cuba", dial: "+53", iso: "CU" },
  { name: "Cyprus", dial: "+357", iso: "CY" },
  { name: "Czech Republic", dial: "+420", iso: "CZ" },
  { name: "Denmark", dial: "+45", iso: "DK" },
  { name: "Djibouti", dial: "+253", iso: "DJ" },
  { name: "Dominica", dial: "+1767", iso: "DM" },
  { name: "Dominican Republic", dial: "+1849", iso: "DO" },
  { name: "Dominican Republic", dial: "+1809", iso: "DO" },
  { name: "Ecuador", dial: "+593", iso: "EC" },
  { name: "Egypt", dial: "+20", iso: "EG" },
  { name: "El Salvador", dial: "+503", iso: "SV" },
  { name: "Equatorial Guinea", dial: "+240", iso: "GQ" },
  { name: "Eritrea", dial: "+291", iso: "ER" },
  { name: "Estonia", dial: "+372", iso: "EE" },
  { name: "Ethiopia", dial: "+251", iso: "ET" },
  { name: "Falkland Islands (Malvinas)", dial: "+500", iso: "FK" },
  { name: "Faroe Islands", dial: "+298", iso: "FO" },
  { name: "Fiji", dial: "+679", iso: "FJ" },
  { name: "Finland", dial: "+358", iso: "FI" },
  { name: "France", dial: "+33", iso: "FR" },
  { name: "French Guiana", dial: "+594", iso: "GF" },
  { name: "French Polynesia", dial: "+689", iso: "PF" },
  { name: "Gabon", dial: "+241", iso: "GA" },
  { name: "Gambia", dial: "+220", iso: "GM" },
  { name: "Georgia", dial: "+995", iso: "GE" },
  { name: "Germany", dial: "+49", iso: "DE" },
  { name: "Ghana", dial: "+233", iso: "GH" },
  { name: "Gibraltar", dial: "+350", iso: "GI" },
  { name: "Greece", dial: "+30", iso: "GR" },
  { name: "Greenland", dial: "+299", iso: "GL" },
  { name: "Grenada", dial: "+1473", iso: "GD" },
  { name: "Guadeloupe", dial: "+590", iso: "GP" },
  { name: "Guam", dial: "+1671", iso: "GU" },
  { name: "Guatemala", dial: "+502", iso: "GT" },
  { name: "Guernsey", dial: "+44", iso: "GG" },
  { name: "Guinea", dial: "+224", iso: "GN" },
  { name: "Guinea-Bissau", dial: "+245", iso: "GW" },
  { name: "Guyana", dial: "+595", iso: "GY" },
  { name: "Haiti", dial: "+509", iso: "HT" },
  { name: "Holy See (Vatican City State)", dial: "+379", iso: "VA" },
  { name: "Honduras", dial: "+504", iso: "HN" },
  { name: "Hong Kong", dial: "+852", iso: "HK" },
  { name: "Hungary", dial: "+36", iso: "HU" },
  { name: "Iceland", dial: "+354", iso: "IS" },
  { name: "Indonesia", dial: "+62", iso: "ID" },
  { name: "Iran, Islamic Republic of Persian Gulf", dial: "+98", iso: "IR" },
  { name: "Iraq", dial: "+964", iso: "IQ" },
  { name: "Ireland", dial: "+353", iso: "IE" },
  { name: "Isle of Man", dial: "+44", iso: "IM" },
  { name: "Israel", dial: "+972", iso: "IL" },
  { name: "Italy", dial: "+39", iso: "IT" },
  { name: "Jamaica", dial: "+1876", iso: "JM" },
  { name: "Japan", dial: "+81", iso: "JP" },
  { name: "Jersey", dial: "+44", iso: "JE" },
  { name: "Jordan", dial: "+962", iso: "JO" },
  { name: "Kazakhstan", dial: "+77", iso: "KZ" },
  { name: "Kenya", dial: "+254", iso: "KE" },
  { name: "Kiribati", dial: "+686", iso: "KI" },
  { name: "Korea, Democratic People's Republic of Korea", dial: "+850", iso: "KP" },
  { name: "Korea, Republic of South Korea", dial: "+82", iso: "KR" },
  { name: "Kuwait", dial: "+965", iso: "KW" },
  { name: "Kyrgyzstan", dial: "+996", iso: "KG" },
  { name: "Laos", dial: "+856", iso: "LA" },
  { name: "Latvia", dial: "+371", iso: "LV" },
  { name: "Lebanon", dial: "+961", iso: "LB" },
  { name: "Lesotho", dial: "+266", iso: "LS" },
  { name: "Liberia", dial: "+231", iso: "LR" },
  { name: "Libyan Arab Jamahiriya", dial: "+218", iso: "LY" },
  { name: "Liechtenstein", dial: "+423", iso: "LI" },
  { name: "Lithuania", dial: "+370", iso: "LT" },
  { name: "Luxembourg", dial: "+352", iso: "LU" },
  { name: "Macao", dial: "+853", iso: "MO" },
  { name: "Macedonia", dial: "+389", iso: "MK" },
  { name: "Madagascar", dial: "+261", iso: "MG" },
  { name: "Malawi", dial: "+265", iso: "MW" },
  { name: "Malaysia", dial: "+60", iso: "MY" },
  { name: "Maldives", dial: "+960", iso: "MV" },
  { name: "Mali", dial: "+223", iso: "ML" },
  { name: "Malta", dial: "+356", iso: "MT" },
  { name: "Marshall Islands", dial: "+692", iso: "MH" },
  { name: "Martinique", dial: "+596", iso: "MQ" },
  { name: "Mauritania", dial: "+222", iso: "MR" },
  { name: "Mauritius", dial: "+230", iso: "MU" },
  { name: "Mayotte", dial: "+262", iso: "YT" },
  { name: "Mexico", dial: "+52", iso: "MX" },
  { name: "Micronesia, Federated States of Micronesia", dial: "+691", iso: "FM" },
  { name: "Moldova", dial: "+373", iso: "MD" },
  { name: "Monaco", dial: "+377", iso: "MC" },
  { name: "Mongolia", dial: "+976", iso: "MN" },
  { name: "Montenegro", dial: "+382", iso: "ME" },
  { name: "Montserrat", dial: "+1664", iso: "MS" },
  { name: "Morocco", dial: "+212", iso: "MA" },
  { name: "Mozambique", dial: "+258", iso: "MZ" },
  { name: "Myanmar", dial: "+95", iso: "MM" },
  { name: "Namibia", dial: "+264", iso: "NA" },
  { name: "Nauru", dial: "+674", iso: "NR" },
  { name: "Nepal", dial: "+977", iso: "NP" },
  { name: "Netherlands", dial: "+31", iso: "NL" },
  { name: "Netherlands Antilles", dial: "+599", iso: "AN" },
  { name: "New Caledonia", dial: "+687", iso: "NC" },
  { name: "New Zealand", dial: "+64", iso: "NZ" },
  { name: "Nicaragua", dial: "+505", iso: "NI" },
  { name: "Niger", dial: "+227", iso: "NE" },
  { name: "Nigeria", dial: "+234", iso: "NG" },
  { name: "Niue", dial: "+683", iso: "NU" },
  { name: "Norfolk Island", dial: "+672", iso: "NF" },
  { name: "Northern Mariana Islands", dial: "+1670", iso: "MP" },
  { name: "Norway", dial: "+47", iso: "NO" },
  { name: "Oman", dial: "+968", iso: "OM" },
  { name: "Pakistan", dial: "+92", iso: "PK" },
  { name: "Palau", dial: "+680", iso: "PW" },
  { name: "Palestinian Territory, Occupied", dial: "+970", iso: "PS" },
  { name: "Panama", dial: "+507", iso: "PA" },
  { name: "Papua New Guinea", dial: "+675", iso: "PG" },
  { name: "Paraguay", dial: "+595", iso: "PY" },
  { name: "Peru", dial: "+51", iso: "PE" },
  { name: "Philippines", dial: "+63", iso: "PH" },
  { name: "Pitcairn", dial: "+872", iso: "PN" },
  { name: "Poland", dial: "+48", iso: "PL" },
  { name: "Portugal", dial: "+351", iso: "PT" },
  { name: "Puerto Rico", dial: "+1939", iso: "PR" },
  { name: "Qatar", dial: "+974", iso: "QA" },
  { name: "Romania", dial: "+40", iso: "RO" },
  { name: "Russia", dial: "+7", iso: "RU" },
  { name: "Rwanda", dial: "+250", iso: "RW" },
  { name: "Reunion", dial: "+262", iso: "RE" },
  { name: "Saint Barthelemy", dial: "+590", iso: "BL" },
  { name: "Saint Helena, Ascension and Tristan Da Cunha", dial: "+290", iso: "SH" },
  { name: "Saint Kitts and Nevis", dial: "+1869", iso: "KN" },
  { name: "Saint Lucia", dial: "+1758", iso: "LC" },
  { name: "Saint Martin", dial: "+590", iso: "MF" },
  { name: "Saint Pierre and Miquelon", dial: "+508", iso: "PM" },
  { name: "Saint Vincent and the Grenadines", dial: "+1784", iso: "VC" },
  { name: "Samoa", dial: "+685", iso: "WS" },
  { name: "San Marino", dial: "+378", iso: "SM" },
  { name: "Sao Tome and Principe", dial: "+239", iso: "ST" },
  { name: "Saudi Arabia", dial: "+966", iso: "SA" },
  { name: "Senegal", dial: "+221", iso: "SN" },
  { name: "Serbia", dial: "+381", iso: "RS" },
  { name: "Seychelles", dial: "+248", iso: "SC" },
  { name: "Sierra Leone", dial: "+232", iso: "SL" },
  { name: "Singapore", dial: "+65", iso: "SG" },
  { name: "Slovakia", dial: "+421", iso: "SK" },
  { name: "Slovenia", dial: "+386", iso: "SI" },
  { name: "Solomon Islands", dial: "+677", iso: "SB" },
  { name: "Somalia", dial: "+252", iso: "SO" },
  { name: "South Africa", dial: "+27", iso: "ZA" },
  { name: "South Sudan", dial: "+211", iso: "SS" },
  { name: "South Georgia and the South Sandwich Islands", dial: "+500", iso: "GS" },
  { name: "Spain", dial: "+34", iso: "ES" },
  { name: "Sri Lanka", dial: "+94", iso: "LK" },
  { name: "Sudan", dial: "+249", iso: "SD" },
  { name: "Suriname", dial: "+597", iso: "SR" },
  { name: "Svalbard and Jan Mayen", dial: "+47", iso: "SJ" },
  { name: "Swaziland", dial: "+268", iso: "SZ" },
  { name: "Sweden", dial: "+46", iso: "SE" },
  { name: "Switzerland", dial: "+41", iso: "CH" },
  { name: "Syrian Arab Republic", dial: "+963", iso: "SY" },
  { name: "Taiwan", dial: "+886", iso: "TW" },
  { name: "Tajikistan", dial: "+992", iso: "TJ" },
  { name: "Tanzania, United Republic of Tanzania", dial: "+255", iso: "TZ" },
  { name: "Thailand", dial: "+66", iso: "TH" },
  { name: "Timor-Leste", dial: "+670", iso: "TL" },
  { name: "Togo", dial: "+228", iso: "TG" },
  { name: "Tokelau", dial: "+690", iso: "TK" },
  { name: "Tonga", dial: "+676", iso: "TO" },
  { name: "Trinidad and Tobago", dial: "+1868", iso: "TT" },
  { name: "Tunisia", dial: "+216", iso: "TN" },
  { name: "Turkey", dial: "+90", iso: "TR" },
  { name: "Turkmenistan", dial: "+993", iso: "TM" },
  { name: "Turks and Caicos Islands", dial: "+1649", iso: "TC" },
  { name: "Tuvalu", dial: "+688", iso: "TV" },
  { name: "Uganda", dial: "+256", iso: "UG" },
  { name: "Ukraine", dial: "+380", iso: "UA" },
  { name: "United Arab Emirates", dial: "+971", iso: "AE" },
  { name: "United Kingdom", dial: "+44", iso: "GB" },
  { name: "United States of America", dial: "+1", iso: "US" },
  { name: "Uruguay", dial: "+598", iso: "UY" },
  { name: "Uzbekistan", dial: "+998", iso: "UZ" },
  { name: "Vanuatu", dial: "+678", iso: "VU" },
  { name: "Venezuela, Bolivarian Republic of Venezuela", dial: "+58", iso: "VE" },
  { name: "Vietnam", dial: "+84", iso: "VN" },
  { name: "Virgin Islands, British", dial: "+1284", iso: "VG" },
  { name: "Virgin Islands, U.S.", dial: "+1340", iso: "VI" },
  { name: "Wallis and Futuna", dial: "+681", iso: "WF" },
  { name: "Yemen", dial: "+967", iso: "YE" },
  { name: "Zambia", dial: "+260", iso: "ZM" },
  { name: "Zimbabwe", dial: "+263", iso: "ZW" },
  { name: "Kosovo", dial: "+383", iso: "XK" },
];

/** Default fallback ISD used when a contact has no `phone_isd` on record. */
export const DEFAULT_ISD = "+91";

/**
 * Case-insensitive fuzzy filter — matches BOTH country name and dial code
 * (with or without the leading "+").
 */
export function filterIsdCodes(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return ISD_CODES;
  const qNoPlus = q.replace(/^\+/, "");
  return ISD_CODES.filter((c) => {
    const name = c.name.toLowerCase();
    const dialNoPlus = c.dial.replace(/^\+/, "");
    return (
      name.includes(q) ||
      c.dial.toLowerCase().includes(q) ||
      dialNoPlus.startsWith(qNoPlus)
    );
  });
}
